<div class="es-wrapper-color" style="background-color: rgb(248, 249, 253);">
                                                
                                                <table class="es-wrapper" width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse; border-spacing: 0px; padding: 0px; margin: 0px; width: 100%; height: 100%; background-repeat: repeat; background-position: center top;"><tbody><tr><td valign="top" style="padding: 0px; margin: 0px;">
                                                            <table cellpadding="0" cellspacing="0" class="es-header" align="center" style="border-collapse: collapse; border-spacing: 0px; width: 100%; background-color: transparent; background-repeat: repeat; background-position: center top; table-layout: fixed !important;"><tbody><tr><td align="center" style="padding: 0px; margin: 0px;">
                                                                        <table bgcolor="#ffffff" class="es-header-body" align="center" cellpadding="0" cellspacing="0" style="border-collapse: collapse; border-spacing: 0px; background-color: transparent; width: 600px;"><tbody><tr><td align="left" style="margin: 0px; padding: 10px 30px 15px;">
                                                                                    <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; border-spacing: 0px;"><tbody><tr><td align="center" valign="top" style="padding: 0px; margin: 0px; width: 540px;">
                                                                                                <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; border-spacing: 0px;"><tbody><tr><td align="center" style="padding: 0px; margin: 0px; font-size: 0px;">
                                                                                                            <span class="Object" role="link" id="OBJ_PREFIX_DWT881_com_zimbra_url"><span class="Object" role="link" id="OBJ_PREFIX_DWT884_com_zimbra_url"><a href="https://chaskitour.com" style="text-decoration: underline; color: rgb(19, 118, 200); font-size: 14px;" target="_blank" rel="nofollow noopener noreferrer"><h2>CHASKI TOUR</h2></a></span></span>
                                                                                                        </td></tr></tbody></table>
                                                                                            </td></tr></tbody></table>
                                                                                </td></tr></tbody></table>
                                                                    </td></tr></tbody></table>
                                                            <table cellpadding="0" cellspacing="0" class="es-content" align="center" style="border-collapse: collapse; border-spacing: 0px; width: 100%; table-layout: fixed !important;"><tbody><tr><td align="center" bgcolor="#f8f9fd" style="padding: 0px; margin: 0px; background-color: dark;">
                                                                        <table bgcolor="transparent" class="es-content-body" align="center" cellpadding="0" cellspacing="0" style="border-collapse: collapse; border-spacing: 0px; background-color: transparent; width: 600px;"><tbody><tr><td align="left" style="margin: 0px; padding: 20px 20px 10px;">
                                                                                    <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; border-spacing: 0px;"><tbody><tr><td align="center" valign="top" style="padding: 0px; margin: 0px; width: 560px;">
                                                                                                <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; border-spacing: 0px;"><tbody><tr><td align="center" style="padding: 0px 0px 10px; margin: 0px;">
                                                                                                            <h1 style="margin: 0px; line-height: 36px; font-family: roboto, &quot;helvetica neue&quot;, helvetica, arial, sans-serif; font-size: 30px; font-style: normal; font-weight: bold; color: rgb(33, 33, 33);">
                                                                                                                Hola {{ $name }}, Gracias por ponerte en contacto
                                                                                                            </h1>
                                                                                                        </td></tr><tr><td align="center" style="padding: 10px 0px; margin: 0px;">
                                                                                                            <p style="margin: 0px; font-family: roboto, &quot;helvetica neue&quot;, helvetica, arial, sans-serif; line-height: 24px; color: rgb(19, 19, 19); font-size: 16px;">
                                                                                                                Hemos recepcionado tu mensaje, uno de nuestros asesores se pondrá en contacto contigo para hacer realidad tu proyecto.
                                                                                                            </p>
                                                                                                        </td></tr></tbody></table>
                                                                                            </td></tr></tbody></table>
                                                                                </td></tr><tr><td class="es-m-p15t es-m-p0b es-m-p0r es-m-p0l" align="left" style="padding: 15px 0px 0px; margin: 0px;">
                                                                                    <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; border-spacing: 0px;"><tbody><tr><td align="center" valign="top" style="padding: 0px; margin: 0px; width: 600px;">
                                                                                                <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; border-spacing: 0px;"><tbody><tr><td align="center" style="padding: 0px; margin: 0px; font-size: 0px;">
                                                                                                            <img class="adapt-img" alt="alt" style="display: block; border: 0px; outline: none; text-decoration: none;" width="600" dfsrc="{{ asset('images/bground.jpg') }}" src="{{ asset('images/bground.jpg') }}" saveddisplaymode="block">
                                                                                                        </td></tr></tbody></table>
                                                                                            </td></tr></tbody></table>
                                                                                </td></tr></tbody></table>
                                                                    </td></tr></tbody></table>
                                                            <table cellpadding="0" cellspacing="0" class="es-content" align="center" style="border-collapse: collapse; border-spacing: 0px; width: 100%; table-layout: fixed !important;"><tbody><tr><td align="center" bgcolor="#071f4f" style="padding: 0px; margin: 0px; background-color: rgb(7, 31, 79); background-repeat: no-repeat; background-position: center top;" dfbackground="https://upngfx.stripocdn.email/content/guids/CABINET_1ce849b9d6fc2f13978e163ad3c663df/images/10801592857268437.png" background="https://upngfx.stripocdn.email/content/guids/CABINET_1ce849b9d6fc2f13978e163ad3c663df/images/10801592857268437.png">
                                                                        <table bgcolor="#ffffff" class="es-content-body" align="center" cellpadding="0" cellspacing="0" style="border-collapse: collapse; border-spacing: 0px; background-color: transparent; width: 600px;"><tbody><tr><td align="left" style="margin: 0px; padding: 40px 30px;">
                                                                                    <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; border-spacing: 0px;"><tbody><tr><td align="center" valign="top" style="padding: 0px; margin: 0px; width: 540px;">
                                                                                                <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; border-spacing: 0px;"><tbody><tr><td align="center" height="20" style="padding: 0px; margin: 0px;"></td></tr><tr><td align="left" style="padding: 0px 0px 10px; margin: 0px;">
                                                                                                            <h1 style="margin: 0px; line-height: 36px; font-family: roboto, &quot;helvetica neue&quot;, helvetica, arial, sans-serif; font-size: 30px; font-style: normal; font-weight: bold; color: rgb(255, 255, 255); text-align: center;">
                                                                                                                Chaski Tour - Agencia de Viajes
                                                                                                            </h1>
                                                                                                        </td></tr><tr><td align="center" style="padding: 0px; margin: 0px; font-size: 0px;">
                                                                                                            <table cellpadding="0" cellspacing="0" class="es-table-not-adapt es-social" style="border-collapse: collapse; border-spacing: 0px;"><tbody><tr><td align="center" valign="top" style="padding: 0px 10px 0px 0px; margin: 0px;">
                                                                                                                        <span class="Object" role="link" id="OBJ_PREFIX_DWT882_com_zimbra_url"><span class="Object" role="link" id="OBJ_PREFIX_DWT885_com_zimbra_url"><a href="https://www.facebook.com/agencia360creativemedia" style="text-decoration: underline; color: rgb(44, 181, 67); font-size: 16px;" target="_blank" rel="nofollow noopener noreferrer"><img title="Facebook" alt="Fb" width="32" style="display: block; border: 0px; outline: none; text-decoration: none;" dfsrc="https://upngfx.stripocdn.email/content/assets/img/social-icons/circle-colored/facebook-circle-colored.png" src="https://upngfx.stripocdn.email/content/assets/img/social-icons/circle-colored/facebook-circle-colored.png" saveddisplaymode="block"></a></span></span>
                                                                                                                    </td><td align="center" valign="top" style="padding: 0px; margin: 0px;">
                                                                                                                        <span class="Object" role="link" id="OBJ_PREFIX_DWT883_com_zimbra_url"><span class="Object" role="link" id="OBJ_PREFIX_DWT886_com_zimbra_url"><a href="https://www.instagram.com/360creative_media/" style="text-decoration: underline; color: rgb(44, 181, 67); font-size: 16px;" target="_blank" rel="nofollow noopener noreferrer"><img title="Instagram" alt="Inst" width="32" style="display: block; border: 0px; outline: none; text-decoration: none;" dfsrc="https://upngfx.stripocdn.email/content/assets/img/social-icons/circle-colored/instagram-circle-colored.png" src="https://upngfx.stripocdn.email/content/assets/img/social-icons/circle-colored/instagram-circle-colored.png" saveddisplaymode="block"></a></span></span>
                                                                                                                    </td></tr></tbody></table>
                                                                                                        </td></tr></tbody></table>
                                                                                            </td></tr></tbody></table>
                                                                                </td></tr></tbody></table>
                                                                    </td></tr></tbody></table>
                                                        </td></tr></tbody></table>
                                            </div>